---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx
  description: Example nginx app
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=nginx'
spec:
  type: service
  lifecycle: experimental
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: busybox
  description: Example busybox app
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=busybox'
    'backstage.io/kubernetes-namespace': develop
spec:
  type: service
  lifecycle: experimental
  owner: guests
